# Generated by Django 3.2 on 2023-03-25 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='socials.post'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='media/product-thumbnails'),
        ),
    ]
