# Generated by Django 3.2 on 2023-03-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['-post']},
        ),
    ]
