# Generated by Django 3.2 on 2023-05-02 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socials', '0010_order_ordereditem_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.myuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.myuser'),
            preserve_default=False,
        ),
    ]
