# Generated by Django 3.2 on 2023-05-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0011_auto_20230502_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
