# Generated by Django 3.2 on 2023-05-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0014_comment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/products'),
        ),
    ]
