# Generated by Django 3.2 on 2023-05-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0015_auto_20230510_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='media/product-thumbnails'),
        ),
    ]
