# Generated by Django 3.2 on 2023-05-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0019_product_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='post',
        ),
    ]
