# Generated by Django 3.2 on 2023-05-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0024_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(related_name='message', to='socials.Message'),
        ),
    ]
