# Generated by Django 4.2.3 on 2023-08-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0027_message_owner_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
