# Generated by Django 4.2.3 on 2023-08-29 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0032_alter_post_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='messages',
            field=models.ForeignKey(blank=True, default=14, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='socials.chat'),
        ),
    ]
