# Generated by Django 4.0.3 on 2023-03-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_myuser_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
